version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        restart: unless-stopped
        volumes:
            - .:/var/www
        depends_on:
            - db
            - db_test
        networks:
            - laravel_network
        environment:
            # Основная база данных
            DB_CONNECTION: mysql
            DB_HOST: mysql_db
            DB_PORT: 3306
            DB_DATABASE: laravel
            DB_USERNAME: user
            DB_PASSWORD: password

            # Тестовая база данных
            DB_TEST_CONNECTION: mysql_test
            DB_TEST_HOST: mysql_db_test
            DB_TEST_PORT: 3306
            DB_TEST_DATABASE: laravel_test
            DB_TEST_USERNAME: user
            DB_TEST_PASSWORD: password

    db:
        image: mysql:5.7
        container_name: mysql_db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_USER: user
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - laravel_network
        ports:
            - "3306:3306"

    db_test:
        image: mysql:5.7
        container_name: mysql_db_test
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: laravel_test
            MYSQL_USER: user
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - db_data_test:/var/lib/mysql
        networks:
            - laravel_network
        ports:
            - "3307:3306"

    nginx:
        image: nginx:alpine
        container_name: nginx_server
        restart: unless-stopped
        ports:
            - "80:80"
        volumes:
            - .:/var/www
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - laravel_network

volumes:
    db_data:
    db_data_test:

networks:
    laravel_network:
        driver: bridge
